(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var k;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function da(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var ea=da(this);
function fa(){}fa.prototype.toJSON=function(){return{}};function p(a){a.__shady||(a.__shady=new fa);return a.__shady}function q(a){return a&&a.__shady};var r=window.ShadyDOM||{};r.Gb=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ha=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");r.h=!!(ha&&ha.configurable&&ha.get);r.ga=r.force||!r.Gb;r.j=r.noPatch||!1;r.ja=r.preferPerformance;r.ia="on-demand"===r.j;var ia=navigator.userAgent.match("Trident");r.Ia=ia;function u(a){return(a=q(a))&&void 0!==a.firstChild}function v(a){return a instanceof ShadowRoot}function ja(a){return(a=(a=q(a))&&a.root)&&a.qa()}
var w=Element.prototype,ka=w.matches||w.matchesSelector||w.mozMatchesSelector||w.msMatchesSelector||w.oMatchesSelector||w.webkitMatchesSelector,la=document.createTextNode(""),ma=0,na=[];(new MutationObserver(function(){for(;na.length;)try{na.shift()()}catch(a){throw la.textContent=ma++,a;}})).observe(la,{characterData:!0});function oa(a){na.push(a);la.textContent=ma++}var pa=!!document.contains;function qa(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function ra(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ba(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}function sa(a){var b=[];for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)b.push(a);return b}
function ta(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b.push(a);return b}function ua(a,b,c){c.configurable=!0;if(c.value)a[b]=c.value;else try{Object.defineProperty(a,b,c)}catch(d){}}function x(a,b,c,d){c=void 0===c?"":c;for(var e in b)d&&0<=d.indexOf(e)||ua(a,c+e,b[e])}function va(a,b){for(var c in b)c in a&&ua(a,c,b[c])}function y(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var wa=[],xa;function ya(a){xa||(xa=!0,oa(za));wa.push(a)}function za(){xa=!1;for(var a=!!wa.length;wa.length;)wa.shift()();return a}za.list=wa;function Aa(){this.P=!1;this.addedNodes=[];this.removedNodes=[];this.U=new Set}function Ba(a){a.P||(a.P=!0,oa(function(){a.flush()}))}Aa.prototype.flush=function(){if(this.P){this.P=!1;var a=this.takeRecords();a.length&&this.U.forEach(function(b){b(a)})}};Aa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ca(a,b){var c=p(a);c.J||(c.J=new Aa);c.J.U.add(b);var d=c.J;return{Pa:b,lb:d,kb:a,takeRecords:function(){return d.takeRecords()}}}function Da(a){var b=a&&a.lb;b&&(b.U["delete"](a.Pa),b.U.size||(p(a.kb).J=null))}
function Ea(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Fa=/[&\u00A0"]/g,Ga=/[&\u00A0<>]/g;function Ha(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ia(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ja=Ia("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ka=Ia("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function La(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var m=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:m=h.localName;for(var n="<"+m,t=h.attributes,B=0,Pa;Pa=t[B];B++)n+=" "+Pa.name+'="'+Pa.value.replace(Fa,Ha)+'"';n+=">";h=Ja[m]?n:n+La(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&Ka[m.localName]?h:h.replace(Ga,Ha);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Ma=r.h,Na={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Oa={};function Qa(a){Oa[a]=function(b){return b["__shady_native_"+a]}}function Ra(a,b){x(a,b,"__shady_native_");for(var c in b)Qa(c)}function z(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Na[d]||(Na[d]=e.value):Qa(d))}}
var A=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),C=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Sa=document.implementation.createHTMLDocument("inert");function Ta(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Ua=["firstElementChild","lastElementChild","children","childElementCount"],Va=["querySelector","querySelectorAll"];
function Wa(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?z(window.EventTarget.prototype,a):(z(Node.prototype,a),z(Window.prototype,a));Ma?z(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Ra(Node.prototype,{parentNode:{get:function(){A.currentNode=this;return A.parentNode()}},firstChild:{get:function(){A.currentNode=this;return A.firstChild()}},lastChild:{get:function(){A.currentNode=
this;return A.lastChild()}},previousSibling:{get:function(){A.currentNode=this;return A.previousSibling()}},nextSibling:{get:function(){A.currentNode=this;return A.nextSibling()}},childNodes:{get:function(){var b=[];A.currentNode=this;for(var c=A.firstChild();c;)b.push(c),c=A.nextSibling();return b}},parentElement:{get:function(){C.currentNode=this;return C.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Ta(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});z(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
z(HTMLElement.prototype,["parentElement","contains"]);a={firstElementChild:{get:function(){C.currentNode=this;return C.firstChild()}},lastElementChild:{get:function(){C.currentNode=this;return C.lastChild()}},children:{get:function(){var b=[];C.currentNode=this;for(var c=C.firstChild();c;)b.push(c),c=C.nextSibling();return ra(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Ma?(z(Element.prototype,Ua),z(Element.prototype,["previousElementSibling","nextElementSibling",
"innerHTML","className"]),z(HTMLElement.prototype,["children","innerHTML","className"])):(Ra(Element.prototype,a),Ra(Element.prototype,{previousElementSibling:{get:function(){C.currentNode=this;return C.previousSibling()}},nextElementSibling:{get:function(){C.currentNode=this;return C.nextSibling()}},innerHTML:{get:function(){return La(this,sa)},set:function(b){var c="template"===this.localName?this.content:this;Ta(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Sa.namespaceURI?
Sa.createElementNS(this.namespaceURI,d):Sa.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}},className:{get:function(){return this.getAttribute("class")||""},set:function(b){this.setAttribute("class",b)}}}));z(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));z(Element.prototype,Va);z(HTMLElement.prototype,["focus","blur"]);window.HTMLTemplateElement&&
z(window.HTMLTemplateElement.prototype,["innerHTML"]);Ma?z(DocumentFragment.prototype,Ua):Ra(DocumentFragment.prototype,a);z(DocumentFragment.prototype,Va);Ma?(z(Document.prototype,Ua),z(Document.prototype,["activeElement"])):Ra(Document.prototype,a);z(Document.prototype,["importNode","getElementById"]);z(Document.prototype,Va)};var Xa=y({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get shadowRoot(){return this.__shady_shadowRoot}}),Ya=y({get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=
a},get innerHTML(){return this.__shady_innerHTML},set innerHTML(a){return this.__shady_innerHTML=a}}),Za=y({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}});function $a(a){for(var b in a){var c=a[b];c&&(c.enumerable=!1)}}$a(Xa);$a(Ya);$a(Za);var ab=r.h||!0===r.j,bb=ab?function(){}:function(a){var b=p(a);b.La||(b.La=!0,va(a,Za))},cb=ab?function(){}:function(a){var b=p(a);b.Ka||(b.Ka=!0,va(a,Xa),window.customElements&&window.customElements.polyfillWrapFlushCallback&&!r.j||va(a,Ya))};var db="__eventWrappers"+Date.now(),eb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),fb=function(){function a(){}var b=!1,c={get capture(){b=!0;return!1}};window.addEventListener("test",a,c);window.removeEventListener("test",a,c);return b}();function gb(a){if(a&&"object"===typeof a){var b=!!a.capture;var c=!!a.once;var d=!!a.passive;var e=a.B}else b=!!a,d=c=!1;return{Fa:e,capture:b,once:c,passive:d,Ea:fb?a:b}}
var hb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,
drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},ib={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};function jb(a){return a instanceof Node?a.__shady_getRootNode():a}
function kb(a,b){var c=[],d=a;for(a=jb(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function lb(a){a.__composedPath||(a.__composedPath=kb(a.target,!0));return a.__composedPath}function mb(a,b){if(!v)return a;a=kb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=jb(d),f!==e&&(g=a.indexOf(f),e=f),!v(f)||-1<g)return d}
function nb(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var ob={focus:!0,blur:!0};function pb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}function qb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!pb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function rb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];qb(a,d,"capture");if(a.X)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=q(d);f=f&&f.root;if(0===c||f&&f===e)if(qb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.X)break}}
function sb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],m=h.type,l=h.capture,n=h.once,t=h.passive;if(b===h.node&&c===m&&d===l&&e===n&&f===t)return g}return-1}function tb(a){za();return this.__shady_native_dispatchEvent(a)}
function ub(a,b,c){var d=gb(c),e=d.capture,f=d.once,g=d.passive,h=d.Fa;d=d.Ea;if(b){var m=typeof b;if("function"===m||"object"===m)if("object"!==m||b.handleEvent&&"function"===typeof b.handleEvent){if(ib[a])return this.__shady_native_addEventListener(a,b,d);var l=h||this;if(h=b[db]){if(-1<sb(h,l,a,e,f,g))return}else b[db]=[];h=function(n){f&&this.__shady_removeEventListener(a,b,c);n.__target||vb(n);if(l!==this){var t=Object.getOwnPropertyDescriptor(n,"currentTarget");Object.defineProperty(n,"currentTarget",
{get:function(){return l},configurable:!0})}n.__previousCurrentTarget=n.currentTarget;if(!v(l)&&"slot"!==l.localName||-1!=n.composedPath().indexOf(l))if(n.composed||-1<n.composedPath().indexOf(l))if(pb(n)&&n.target===n.relatedTarget)n.eventPhase===Event.BUBBLING_PHASE&&n.stopImmediatePropagation();else if(n.eventPhase===Event.CAPTURING_PHASE||n.bubbles||n.target===l||l instanceof Window){var B="function"===m?b.call(l,n):b.handleEvent&&b.handleEvent(n);l!==this&&(t?(Object.defineProperty(n,"currentTarget",
t),t=null):delete n.currentTarget);return B}};b[db].push({node:l,type:a,capture:e,once:f,passive:g,Ub:h});ob[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(h)):this.__shady_native_addEventListener(a,h,d)}}}
function wb(a,b,c){if(b){var d=gb(c);c=d.capture;var e=d.once,f=d.passive,g=d.Fa;d=d.Ea;if(ib[a])return this.__shady_native_removeEventListener(a,b,d);var h=g||this;g=void 0;var m=null;try{m=b[db]}catch(l){}m&&(e=sb(m,h,a,c,e,f),-1<e&&(g=m.splice(e,1)[0].Ub,m.length||(b[db]=void 0)));this.__shady_native_removeEventListener(a,g||b,d);g&&ob[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][c?"capture":"bubble"],b=a.indexOf(g),-1<b&&a.splice(b,1))}}
function xb(){for(var a in ob)window.__shady_native_addEventListener(a,function(b){b.__target||(vb(b),rb(b))},!0)}
var yb=y({get composed(){void 0===this.__composed&&(eb?this.__composed="focusin"===this.type||"focusout"===this.type||eb(this):!1!==this.isTrusted&&(this.__composed=hb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=kb(this.__target,this.composed));return this.__composedPath},get target(){return mb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=kb(this.__relatedTarget,!0));return mb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.X=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.X=this.__immediatePropagationStopped=!0}});
function vb(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(r.h){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;x(c,yb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else x(a,yb)}var zb=nb(Event),Ab=nb(CustomEvent),Bb=nb(MouseEvent);
function Cb(){if(!eb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var Db=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function Eb(a,b){return{index:a,K:[],T:b}}
function Fb(a,b,c,d){var e=0,f=0,g=0,h=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,n=0;n<m-g&&Gb(a[--h],c[--l]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Eb(e,0);f<d;)b.K.push(c[f++]);return[b]}if(f==d)return[Eb(e,b-e)];m=e;g=f;d=d-g+1;h=b-m+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(n=1;n<h;n++)if(a[m+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var t=b[l-1][n]+1,B=b[l][n-1]+1;b[l][n]=t<B?t:B}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)0==m?(a.push(2),g--):0==g?(a.push(3),m--):(h=b[m-1][g-1],l=b[m-1][g],n=b[m][g-1],t=l<n?l<h?l:h:n<h?n:h,t==h?(h==d?a.push(0):(a.push(1),d=h),m--,g--):t==l?(a.push(3),m--,d=l):(a.push(2),g--,d=n));a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Eb(e,0));b.T++;e++;b.K.push(c[f]);f++;break;case 2:b||(b=Eb(e,0));
b.T++;e++;break;case 3:b||(b=Eb(e,0)),b.K.push(c[f]),f++}b&&m.push(b);return m}function Gb(a,b){return a===b};var Hb=y({dispatchEvent:tb,addEventListener:ub,removeEventListener:wb});var Ib=null;function D(){Ib||(Ib=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Ib||null}function Jb(a,b,c){var d=D();return d&&"class"===b?(d.setElementClass(a,c),!0):!1}function Kb(a,b){var c=D();c&&c.unscopeNode(a,b)}function Lb(a,b){var c=D();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)c=c&&Lb(a,b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}
function Mb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=D();return b?b.currentScopeForNode(a):""}function Nb(a,b){if(a)for(a.nodeType===Node.ELEMENT_NODE&&b(a),a=a.__shady_firstChild;a;a=a.__shady_nextSibling)a.nodeType===Node.ELEMENT_NODE&&Nb(a,b)};var Ob=window.document,Pb=r.ja,Qb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Rb=Qb&&Qb.get;function Sb(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Tb(a){var b=q(a);if(b&&void 0!==b.W)for(b=a.__shady_firstChild;b;b=b.__shady_nextSibling)Tb(b);if(a=q(a))a.W=void 0}function Ub(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=q(a))&&b.G)&&b.length?b[0]:Ub(a.__shady_nextSibling));return b}
function Vb(a,b,c){if(a=(a=q(a))&&a.J){if(b)if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(var d=0,e=b.childNodes.length;d<e;d++)a.addedNodes.push(b.childNodes[d]);else a.addedNodes.push(b);c&&a.removedNodes.push(c);Ba(a)}}
var Yb=y({get parentNode(){var a=q(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=q(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=q(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=q(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=q(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(u(this)){var a=q(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=q(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Rb&&Rb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(pa){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(v(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(u(this)){for(var a=[],b=this.__shady_firstChild;b;b=b.__shady_nextSibling)b.nodeType!==Node.COMMENT_NODE&&a.push(b.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!u(this)&&r.h){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Sb(this);this.__shady_native_textContent=a}else Sb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Ob&&a.ownerDocument!==Ob)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=q(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;Vb(this,a);var d=[],e=(c=E(this))?c.host.localName:Mb(this),f=a.__shady_parentNode;if(f){var g=Mb(a);var h=!!c||!E(a)||
Pb&&void 0!==this.__noInsertionPoint;f.__shady_removeChild(a,h)}f=!0;var m=(!Pb||void 0===a.__noInsertionPoint&&void 0===this.__noInsertionPoint)&&!Lb(a,e),l=c&&!a.__noInsertionPoint&&(!Pb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(l||m)m&&(g=g||Mb(a)),Nb(a,function(n){l&&"slot"===n.localName&&d.push(n);if(m){var t=g;D()&&(t&&Kb(n,t),(t=D())&&t.scopeNode(n,e))}});d.length&&(c.ma(d),c.o());u(this)&&(Wb(a,this,b),c=q(this),ja(this)?(c.root.o(),f=!1):c.root&&(f=!1));f?(c=v(this)?this.host:this,b?
(b=Ub(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);return a},appendChild:function(a){if(this!=a||!v(a))return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Ob)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);Vb(this,null,a);var c=E(a),d=c&&c.ob(a),e=q(this);
if(u(this)&&(Xb(a,this),ja(this))){e.root.o();var f=!0}if(D()&&!b&&c&&a.nodeType!==Node.TEXT_NODE){var g=Mb(a);Nb(a,function(h){Kb(h,g)})}Tb(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&c.o());f||(f=v(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_firstChild;for(var c;a;a=a.__shady_nextSibling)c=a.__shady_cloneNode(!0),b.__shady_appendChild(c)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=p(this),c=b.W;void 0===c&&(v(this)?(c=this,b.W=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.W=c)));return c}},contains:function(a){return qa(this,a)}});var Zb=y({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&a.O();return(a=q(this))&&a.assignedSlot||null}});function $b(a,b,c){var d=[];ac(a,b,c,d);return d}function ac(a,b,c,d){for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling){var e;if(e=a.nodeType===Node.ELEMENT_NODE){e=a;var f=b,g=c,h=d,m=f(e);m&&h.push(e);g&&g(m)?e=m:(ac(e,f,g,h),e=void 0)}if(e)break}}
var F=y({get firstElementChild(){var a=q(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=q(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return u(this)?ra(Array.prototype.filter.call(ta(this),
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),bc=y({querySelector:function(a){return $b(this,function(b){return ka.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return ra(b.filter(function(d){return d.__shady_getRootNode()==c}))}return ra($b(this,function(d){return ka.call(d,
a)}))}}),cc=r.ja&&!r.j?Object.assign({},F):F;Object.assign(F,bc);var dc=window.document;function ec(a,b){"slot"===b?(a=a.__shady_parentNode,ja(a)&&q(a).root.o()):"slot"===a.localName&&"name"===b&&(b=E(a))&&(b.Bb(a),b.o())}
var fc=y({get previousElementSibling(){var a=q(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=q(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){this.ownerDocument!==dc?this.__shady_native_setAttribute(a,b):Jb(this,a,b)||(this.__shady_native_setAttribute(a,b),ec(this,a))},removeAttribute:function(a){this.ownerDocument!==dc?this.__shady_native_removeAttribute(a):Jb(this,a,"")?""===this.getAttribute(a)&&this.__shady_native_removeAttribute(a):(this.__shady_native_removeAttribute(a),
ec(this,a))}}),jc=y({attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");if(a.shadyUpgradeFragment&&!r.Ia){var b=a.shadyUpgradeFragment;b.__proto__=ShadowRoot.prototype;b.sa(this,a);gc(b,b);a=b.__noInsertionPoint?null:b.querySelectorAll("slot");b.__noInsertionPoint=void 0;a&&a.length&&(b.ma(a),b.o());b.host.__shady_native_appendChild(b)}else b=new hc(ic,this,a);return this.__CE_shadowRoot=b},get shadowRoot(){var a=q(this);return a&&a.Mb||
null}});Object.assign(fc,jc);var kc=document.implementation.createHTMLDocument("inert"),lc=y({get innerHTML(){return u(this)?La("template"===this.localName?this.content:this,ta):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Sb(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==kc.namespaceURI?kc.createElementNS(this.namespaceURI,b):kc.createElement(b);for(r.h?b.__shady_native_innerHTML=a:b.innerHTML=a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var mc=y({blur:function(){var a=q(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});r.ja||Db.forEach(function(a){mc[a]={set:function(b){var c=p(this),d=a.substring(2);c.A||(c.A={});c.A[a]&&this.removeEventListener(d,c.A[a]);this.__shady_addEventListener(d,b);c.A[a]=b},get:function(){var b=q(this);return b&&b.A&&b.A[a]},configurable:!0}});var nc=y({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&v(b)&&b.O();return(b=q(this))?(a&&a.flatten?b.G:b.assignedNodes)||[]:[]}},addEventListener:function(a,b,c){if("slot"!==this.localName||"slotchange"===a)ub.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.B=this;d.__shady_addEventListener(a,b,c)}},removeEventListener:function(a,
b,c){if("slot"!==this.localName||"slotchange"===a)wb.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.B=this;d.__shady_removeEventListener(a,b,c)}}});var oc=y({getElementById:function(a){return""===a?null:$b(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var pc=y({get activeElement(){var a=r.h?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!v(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=E(a);b&&b!==this;)a=b.host,b=E(a);return this===document?b?null:a:b===this?a:null}});var qc=window.document,rc=y({importNode:function(a,b){if(a.ownerDocument!==qc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b)for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b=this.__shady_importNode(a,!0),c.__shady_appendChild(b);return c}});var sc=y({dispatchEvent:tb,addEventListener:ub.bind(window),removeEventListener:wb.bind(window)});var G={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(G.parentElement=Yb.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(G.contains=Yb.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(G.children=F.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(G.innerHTML=lc.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(G.className=fc.className);
var H={EventTarget:[Hb],Node:[Yb,window.EventTarget?null:Hb],Text:[Zb],Comment:[Zb],CDATASection:[Zb],ProcessingInstruction:[Zb],Element:[fc,F,Zb,!r.h||"innerHTML"in Element.prototype?lc:null,window.HTMLSlotElement?null:nc],HTMLElement:[mc,G],HTMLSlotElement:[nc],DocumentFragment:[cc,oc],Document:[rc,cc,oc,pc],Window:[sc]},tc=r.h?null:["innerHTML","textContent"];function I(a,b,c,d){b.forEach(function(e){return a&&e&&x(a,e,c,d)})}
function uc(a){var b=a?null:tc,c;for(c in H)I(window[c]&&window[c].prototype,H[c],a,b)}["Text","Comment","CDATASection","ProcessingInstruction"].forEach(function(a){var b=window[a],c=Object.create(b.prototype);c.__shady_protoIsPatched=!0;I(c,H.EventTarget);I(c,H.Node);H[a]&&I(c,H[a]);b.prototype.__shady_patchedProto=c});function vc(a){a.__shady_protoIsPatched=!0;I(a,H.EventTarget);I(a,H.Node);I(a,H.Element);I(a,H.HTMLElement);I(a,H.HTMLSlotElement);return a};var wc=r.ia,xc=r.h;function yc(a,b){if(wc&&!a.__shady_protoIsPatched&&!v(a)){var c=Object.getPrototypeOf(a),d=c.hasOwnProperty("__shady_patchedProto")&&c.__shady_patchedProto;d||(d=Object.create(c),vc(d),c.__shady_patchedProto=d);Object.setPrototypeOf(a,d)}xc||(1===b?bb(a):2===b&&cb(a))}
function zc(a,b,c,d){yc(a,1);d=d||null;var e=p(a),f=d?p(d):null;e.previousSibling=d?f.previousSibling:b.__shady_lastChild;if(f=q(e.previousSibling))f.nextSibling=a;if(f=q(e.nextSibling=d))f.previousSibling=a;e.parentNode=b;d?d===c.firstChild&&(c.firstChild=a):(c.lastChild=a,c.firstChild||(c.firstChild=a));c.childNodes=null}
function Wb(a,b,c){yc(b,2);var d=p(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)zc(a,b,d,c);else zc(a,b,d,c)}
function Xb(a,b){var c=p(a);b=p(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(p(a).nextSibling=d);d&&(p(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function gc(a,b){var c=p(a);if(b||void 0===c.firstChild){c.childNodes=null;var d=c.firstChild=a.__shady_native_firstChild;c.lastChild=a.__shady_native_lastChild;yc(a,2);c=d;for(d=void 0;c;c=c.__shady_native_nextSibling){var e=p(c);e.parentNode=b||a;e.nextSibling=c.__shady_native_nextSibling;e.previousSibling=d||null;d=c;yc(c,1)}}};var Ac=y({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.B=c.B||this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.B=c.B||this;this.host.__shady_removeEventListener(a,b,c)}});function Bc(a,b){x(a,Ac,b);x(a,pc,b);x(a,lc,b);x(a,F,b);r.j&&!b?(x(a,Yb,b),x(a,oc,b)):r.h||(x(a,Za),x(a,Xa),x(a,Ya))};var ic={},J=r.deferConnectionCallbacks&&"loading"===document.readyState,Cc;function Dc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}function hc(a,b,c){if(a!==ic)throw new TypeError("Illegal constructor");this.a=null;this.sa(b,c)}k=hc.prototype;
k.sa=function(a,b){this.host=a;this.mode=b&&b.mode;gc(this.host);a=p(this.host);a.root=this;a.Mb="closed"!==this.mode?this:null;a=p(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;if(r.preferPerformance)for(;a=this.host.__shady_native_firstChild;)this.host.__shady_native_removeChild(a);else this.o()};k.o=function(){var a=this;this.D||(this.D=!0,ya(function(){return a.O()}))};k.cb=function(){for(var a,b=this;b;)b.D&&(a=b),b=b.bb();return a};
k.bb=function(){var a=this.host.__shady_getRootNode();if(v(a)){var b=q(this.host);if(b&&0<b.N)return a}};k.O=function(){var a=this.D&&this.cb();a&&a._renderSelf()};k.Ya=function(){!this.ra&&this.D&&this.O()};
k._renderSelf=function(){var a=J;J=!0;this.D=!1;this.a&&(this.Ta(),this.Ra());if(!r.preferPerformance&&!this.ra)for(var b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling){var c=q(b);b.__shady_native_parentNode!==this.host||"slot"!==b.localName&&c.assignedSlot||this.host.__shady_native_removeChild(b)}this.ra=!0;J=a;Cc&&Cc()};
k.Ta=function(){this.S();for(var a=0,b;a<this.a.length;a++)b=this.a[a],this.Qa(b);for(a=this.host.__shady_firstChild;a;a=a.__shady_nextSibling)this.oa(a);for(a=0;a<this.a.length;a++){b=this.a[a];var c=q(b);if(!c.assignedNodes.length)for(var d=b.__shady_firstChild;d;d=d.__shady_nextSibling)this.oa(d,b);(d=(d=q(b.__shady_parentNode))&&d.root)&&(d.qa()||d.D)&&d._renderSelf();this.la(c.G,c.assignedNodes);if(d=c.wa){for(var e=0;e<d.length;e++)q(d[e]).ba=null;c.wa=null;d.length>c.assignedNodes.length&&
(c.fa=!0)}c.fa&&(c.fa=!1,this.pa(b))}};k.oa=function(a,b){var c=p(a),d=c.ba;c.ba=null;b||(b=(b=this.c[a.__shady_slot||"__catchall"])&&b[0]);b?(p(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;d!==c.assignedSlot&&c.assignedSlot&&(p(c.assignedSlot).fa=!0)};k.Qa=function(a){var b=q(a),c=b.assignedNodes;b.assignedNodes=[];b.G=[];if(b.wa=c)for(b=0;b<c.length;b++){var d=q(c[b]);d.ba=d.assignedSlot;d.assignedSlot===a&&(d.assignedSlot=null)}};
k.la=function(a,b){for(var c=0,d=void 0;c<b.length&&(d=b[c]);c++)if("slot"==d.localName){var e=q(d).assignedNodes;e&&e.length&&this.la(a,e)}else a.push(b[c])};k.pa=function(a){a.__shady_native_dispatchEvent(new Event("slotchange"));a=q(a);a.assignedSlot&&this.pa(a.assignedSlot)};k.Ra=function(){for(var a=this.a,b=[],c=0;c<a.length;c++){var d=a[c].__shady_parentNode,e=q(d);e&&e.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.Ab(c===this?this.host:c,this.Sa(c))};
k.Sa=function(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)if(this.fb(a))for(var c=q(a).G,d=0;d<c.length;d++)b.push(c[d]);else b.push(a);return b};k.fb=function(a){return"slot"==a.localName};
k.Ab=function(a,b){for(var c=sa(a),d=Fb(b,b.length,c,c.length),e=0,f=0,g=void 0;e<d.length&&(g=d[e]);e++){for(var h=0,m=void 0;h<g.K.length&&(m=g.K[h]);h++)m.__shady_native_parentNode===a&&a.__shady_native_removeChild(m),c.splice(g.index+f,1);f-=g.T}e=0;for(f=void 0;e<d.length&&(f=d[e]);e++)for(g=c[f.index],h=f.index;h<f.index+f.T;h++)m=b[h],a.__shady_native_insertBefore(m,g),c.splice(h,0,m)};k.Xa=function(){this.w=this.w||[];this.a=this.a||[];this.c=this.c||{}};
k.ma=function(a){this.Xa();this.w.push.apply(this.w,a instanceof Array?a:ca(ba(a)))};k.S=function(){this.w&&this.w.length&&(this.ib(this.w),this.w=[])};k.ib=function(a){for(var b,c=0;c<a.length;c++){var d=a[c];gc(d);var e=d.__shady_parentNode;gc(e);e=q(e);e.N=(e.N||0)+1;e=this.ua(d);this.c[e]?(b=b||{},b[e]=!0,this.c[e].push(d)):this.c[e]=[d];this.a.push(d)}if(b)for(var f in b)this.c[f]=this.ya(this.c[f])};k.ua=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.Ma=b};
k.ya=function(a){return a.sort(function(b,c){b=Dc(b);for(var d=Dc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=ta(c.__shady_parentNode),b.indexOf(c)-b.indexOf(f)}})};k.ob=function(a){if(this.a){this.S();var b=this.c,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e];if(qa(a,f)){d.splice(e,1);var g=this.a.indexOf(f);0<=g&&(this.a.splice(g,1),(g=q(f.__shady_parentNode))&&g.N&&g.N--);e--;this.pb(f);g=!0}}return g}};
k.Bb=function(a){if(this.a){this.S();var b=a.Ma,c=this.ua(a);if(c!==b){b=this.c[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.c[c]||(this.c[c]=[]);b.push(a);1<b.length&&(this.c[c]=this.ya(b))}}};k.pb=function(a){a=q(a);var b=a.G;if(b)for(var c=0;c<b.length;c++){var d=b[c],e=d.__shady_native_parentNode;e&&e.__shady_native_removeChild(d)}a.G=[];a.assignedNodes=[]};k.qa=function(){this.S();return!(!this.a||!this.a.length)};
(function(a){a.__proto__=DocumentFragment.prototype;Bc(a,"__shady_");Bc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(hc.prototype);
if(window.customElements&&window.customElements.define&&r.ga&&!r.preferPerformance){var Ec=new Map;Cc=function(){var a=[];Ec.forEach(function(d,e){a.push([e,d])});Ec.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.__shadydom_connectedCallback():c.__shadydom_disconnectedCallback()}};J&&document.addEventListener("readystatechange",function(){J=!1;Cc()},{once:!0});var Fc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.__shadydom_connectedCallback=
function(){J?Ec.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.__shadydom_disconnectedCallback=function(){J?this.isConnected||Ec.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Gc=window.customElements.define,Hc=function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Gc.call(window.customElements,a,Fc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d};window.customElements.define=
Hc;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:Hc,configurable:!0})}function E(a){a=a.__shady_getRootNode();if(v(a))return a};function K(a){this.node=a}k=K.prototype;k.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};k.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};k.appendChild=function(a){return this.node.__shady_appendChild(a)};k.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};k.removeChild=function(a){return this.node.__shady_removeChild(a)};k.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
k.cloneNode=function(a){return this.node.__shady_cloneNode(a)};k.getRootNode=function(a){return this.node.__shady_getRootNode(a)};k.contains=function(a){return this.node.__shady_contains(a)};k.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};k.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};k.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};k.hasAttribute=function(a){return this.node.__shady_native_hasAttribute(a)};k.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};
k.attachShadow=function(a){return this.node.__shady_attachShadow(a)};k.focus=function(){this.node.__shady_native_focus()};k.blur=function(){this.node.__shady_blur()};k.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};k.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};k.querySelector=function(a){return this.node.__shady_querySelector(a)};
k.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};k.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
ea.Object.defineProperties(K.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(v(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(v(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}},className:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_className},set:function(a){return this.node.__shady_className=
a}}});Db.forEach(function(a){Object.defineProperty(K.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var Ic=new WeakMap;function Jc(a){if(v(a)||a instanceof K)return a;var b=Ic.get(a);b||(b=new K(a),Ic.set(a,b));return b};if(r.ga){var Kc=r.h?function(a){return a}:function(a){cb(a);bb(a);return a},ShadyDOM={inUse:r.ga,patch:Kc,isShadyRoot:v,enqueue:ya,flush:za,flushInitial:function(a){a.Ya()},settings:r,filterMutations:Ea,observeChildren:Ca,unobserveChildren:Da,deferConnectionCallbacks:r.deferConnectionCallbacks,preferPerformance:r.preferPerformance,handlesDynamicScoping:!0,wrap:r.j?Jc:Kc,wrapIfNeeded:!0===r.j?Jc:function(a){return a},Wrapper:K,composedPath:lb,noPatch:r.j,patchOnDemand:r.ia,nativeMethods:Na,nativeTree:Oa,
patchElementProto:vc};window.ShadyDOM=ShadyDOM;Wa();uc("__shady_");Object.defineProperty(document,"_activeElement",pc.activeElement);x(Window.prototype,sc,"__shady_");r.j?r.ia&&x(Element.prototype,jc):(uc(),Cb());xb();window.Event=zb;window.CustomEvent=Ab;window.MouseEvent=Bb;window.ShadowRoot=hc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Lc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Mc(a){var b=a=a.replace(Nc,"").replace(Oc,""),c=new Lc;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new Lc;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return Pc(c,a)}
function Pc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(Qc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=4:c.match(Rc)&&(a.type=7,a.keyframesName=a.selector.split(Qc).pop()):a.type=0===c.indexOf("--")?
1E3:1);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Pc(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function Sc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(e))for(var f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=Sc(h,b,d);else b?b=a.cssText:(b=a.cssText,b=b.replace(Tc,"").replace(Uc,""),b=b.replace(Vc,"").replace(Wc,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&0===a.selector.indexOf("--")}var Nc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Oc=/@import[^;]*;/gim,Tc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Uc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Vc=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Wc=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Rc=/^@[^\s]*keyframes/,Qc=/\s+/g;var L=!(window.ShadyDOM&&window.ShadyDOM.inUse),Xc;function Yc(a){Xc=a&&a.shimcssproperties?!1:L||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Zc;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(Zc=window.ShadyCSS.cssBuild);var M=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Xc=window.ShadyCSS.nativeCss:window.ShadyCSS?(Yc(window.ShadyCSS),window.ShadyCSS=void 0):Yc(window.WebComponents&&window.WebComponents.flags);var N=Xc;var $c=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,ad=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,bd=/(--[\w-]+)\s*([:,;)]|$)/gi,cd=/(animation\s*:)|(animation-name\s*:)/,dd=/@media\s(.*)/,ed=/\{[^}]*\}/g;var fd=new Set;function O(a,b){if(!a)return"";"string"===typeof a&&(a=Mc(a));b&&P(a,b);return Sc(a,N)}function gd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Mc(a.textContent));return a.__cssRules||null}function hd(a){return!!a.parent&&7===a.parent.type}function P(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&4===f){var g=a.selector.match(dd);g&&(window.matchMedia(g[1]).matches||(e=!0))}1===f?b(a):c&&7===f?c(a):1E3===f&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)P(g,b,c,d)}}
function id(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;jd(e,c,d);return e}var Q=null;function kd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(Q?Q.nextSibling:null)||b.firstChild);return Q=a}function jd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);Q?a.compareDocumentPosition(Q)===Node.DOCUMENT_POSITION_PRECEDING&&(Q=a):Q=a}
function ld(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function md(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=ld(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=md(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function nd(a,b){L?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var od=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function R(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a["extends"]);return{is:b,L:c}}function pd(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=ld(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function S(a){if(void 0!==Zc)return Zc;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function qd(a){a=void 0===a?"":a;return""!==a&&N?L?"shadow"===a:"shady"===a:!1};function rd(){}function sd(a,b){var c=T;c.R(a,function(d){c.element(d,b||"")})}k=rd.prototype;k.R=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a="template"===a.localName?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.R(a[c],b)};
k.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),nd(a,b)):nd(a,(d?d+" ":"")+"style-scope "+b)}};function td(a,b,c){var d=T;d.R(a,function(e){d.element(e,b,!0);d.element(e,c)})}function ud(a,b){var c=T;c.R(a,function(d){c.element(d,b||"",!0)})}
function vd(a,b,c,d,e){var f=T;e=void 0===e?"":e;""===e&&(L||"shady"===(void 0===d?"":d)?e=O(b,c):(a=R(a),e=wd(f,b,a.is,a.L,c)+"\n\n"));return e.trim()}function wd(a,b,c,d,e){var f=a.Y(c,d);c=a.na(c);return O(b,function(g){g.Jb||(a.za(g,a.da,c,f),g.Jb=!0);e&&e(g,c,f)})}k.na=function(a){return a?"."+a:""};k.Y=function(a,b){return b?"[is="+a+"]":a};k.za=function(a,b,c,d){a.selector=a.i=this.Aa(a,b,c,d)};
k.Aa=function(a,b,c,d){var e=pd(a.selector);if(!hd(a)){a=0;for(var f=e.length,g=void 0;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.filter(function(h){return!!h}).join(",")};k.Ca=function(a){return a.replace(xd,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};
k.nb=function(a){for(var b=[],c;c=a.match(yd);){var d=c.index,e=ld(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ka:a,matches:b}};k.rb=function(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])};
k.da=function(a,b,c){var d=this,e=!1;a=a.trim();var f=xd.test(a);f&&(a=a.replace(xd,function(m,l,n){return":"+l+"("+n.replace(/\s/g,"")+")"}),a=this.Ca(a));var g=yd.test(a);if(g){var h=this.nb(a);a=h.ka;h=h.matches}a=a.replace(zd,":host $1");a=a.replace(Ad,function(m,l,n){e||(m=d.xb(n,l,b,c),e=e||m.stop,l=m.Db,n=m.value);return l+n});g&&(a=this.rb(a,h));f&&(a=this.Ca(a));return a=a.replace(Bd,function(m,l,n,t){return'[dir="'+n+'"] '+l+t+", "+l+'[dir="'+n+'"]'+t})};
k.xb=function(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=this.zb(a,d):0!==e&&(a=c?this.Ba(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Cd,function(g,h){return" > "+h}))}return{value:a,Db:b,stop:f}};k.Ba=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")};
k.zb=function(a,b){var c=a.match(Dd);return(c=c&&c[2].trim()||"")?c[0].match(Ed)?a.replace(Dd,function(d,e,f){return b+f}):c.split(Ed)[0]===b?c:"should_not_match":a.replace(":host",b)};function Fd(a){":root"===a.selector&&(a.selector="html")}k.yb=function(a){return a.match(":host")?"":a.match("::slotted")?this.da(a,":not(.style-scope)"):this.Ba(a.trim(),":not(.style-scope)")};ea.Object.defineProperties(rd.prototype,{M:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var xd=/:(nth[-\w]+)\(([^)]+)\)/,Ad=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Ed=/[[.:#*]/,zd=/^(::slotted)/,Dd=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Cd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Bd=/(.*):dir\((?:(ltr|rtl))\)(.*)/,yd=/:(?:matches|any|-(?:webkit|moz)-any)/,T=new rd;function U(a,b,c,d,e){this.m=a||null;this.placeholder=b||null;this.ha=c||[];this.H=null;this.cssBuild=e||"";this.L=d||"";this.F=this.l=this.v=null}function V(a){return a?a.__styleInfo:null}function Gd(a,b){return a.__styleInfo=b}U.prototype.eb=function(){return this.m};U.prototype._getStyleRules=U.prototype.eb;function Hd(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Id=/:host\s*>\s*/,Jd=navigator.userAgent.match("Trident");function W(){}function Kd(a){var b={},c=[],d=0;P(a,function(f){Ld(f);f.index=d++;f=f.f.cssText;for(var g;g=bd.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.gb=c;a=[];for(var e in b)a.push(e);return a}
function Ld(a){if(!a.f){var b={},c={};Md(a,c)&&(b.u=c,a.rules=null);b.cssText=a.parsedCssText.replace(ed,"").replace($c,"");a.f=b}}function Md(a,b){var c=a.f;if(c){if(c.u)return Object.assign(b,c.u),!0}else{c=a.parsedCssText;for(var d;a=$c.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Nd(a,b,c){b&&(b=0<=b.indexOf(";")?Od(a,b,c):md(b,function(d,e,f,g){if(!e)return d+g;(e=Nd(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Nd(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function Od(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){ad.lastIndex=0;if(f=ad.exec(e))e=Nd(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=Nd(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Pd(a,b){var c={},d=[];P(a,function(e){e.f||Ld(e);var f=e.i||e.parsedSelector;b&&e.f.u&&f&&Hd.call(b,f)&&(Md(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{u:c,key:d}}
function Qd(a,b,c,d){b.f||Ld(b);if(b.f.u){var e=R(a);a=e.is;e=e.L;e=a?T.Y(a,e):"html";var f=b.parsedSelector;var g=!!f.match(Id)||"html"===e&&-1<f.indexOf("html");var h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.i||(b.i=T.Aa(b,T.da,T.na(a),e)),c=b.i||e),g&&"html"===e&&(c=b.i||b.Wb),d({ka:c,Ib:h,Vb:g})}}
function Rd(a,b,c){var d={},e={};P(b,function(f){Qd(a,f,c,function(g){Hd.call(a._element||a,g.ka)&&(g.Ib?Md(f,d):Md(f,e))})},null,!0);return{Nb:e,Hb:d}}
function Sd(a,b,c,d){var e=R(b),f=T.Y(e.is,e.L),g=new RegExp("(?:^|[^.#[:])"+(b["extends"]?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=V(b);e=h.m;h=h.cssBuild;var m=a.Ua(b,e,d);return vd(b,e,function(l){var n="";l.f||Ld(l);l.f.cssText&&(n=Od(a,l.f.cssText,c));l.cssText=n;if(!L&&!hd(l)&&l.cssText){var t=n=l.cssText;null==l.Da&&(l.Da=cd.test(n));if(l.Da)if(null==l.V){l.V=[];for(var B in m)t=m[B],t=t(n),n!==t&&(n=t,l.V.push(B))}else{for(B=0;B<l.V.length;++B)t=m[l.V[B]],n=t(n);t=n}l.cssText=t;a.vb(l,
g,f,d)}},h)}W.prototype.Ua=function(a,b,c){a=b.gb;b={};if(!L&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.ub(e,c),b[e.keyframesName]=this.hb(e);return b};W.prototype.hb=function(a){return function(b){return b.replace(a.Kb,a.Ha)}};W.prototype.ub=function(a,b){a.Kb=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.Ha=a.keyframesName+"-"+b;a.i=a.i||a.selector;a.selector=a.i.replace(a.keyframesName,a.Ha)};
W.prototype.vb=function(a,b,c,d){a.i=a.i||a.selector;d="."+d;for(var e=pd(a.i),f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};function Td(a,b){var c=Ud,d=gd(a);a.textContent=O(d,function(e){var f=e.cssText=e.parsedCssText;e.f&&e.f.cssText&&(f=f.replace(Tc,"").replace(Uc,""),e.cssText=Od(c,f,b))})}ea.Object.defineProperties(W.prototype,{Ja:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ud=new W;var X={},Vd=window.customElements;if(Vd&&!L&&!M){var Wd=Vd.define;Vd.define=function(a,b,c){X[a]||(X[a]=kd(a));Wd.call(Vd,a,b,c)}};function Xd(){this.cache={};this.Sb=100}Xd.prototype.Cb=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.u[e]!==b[e])return!1}return!0};Xd.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({u:b,styleElement:c,l:d});e.length>this.Sb&&e.shift();this.cache[a]=e};Xd.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.Cb(e,b,c))return e}};function Yd(){}var Zd=new RegExp(T.M+"\\s*([^\\s]*)");function $d(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Zd))?a[1]:""}function ae(a){var b=od(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?R(a).is:""}
function be(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=$d(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===S(e)))ud(e,g);else if(f instanceof ShadowRoot)for(f=ae(e),f!==g&&td(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+T.M+")"),g=0;g<e.length;g++){f=e[g];
var h=ae(f);h&&T.element(f,h)}}}}}
if(!(L||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var ce=new MutationObserver(be),de=function(a){ce.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)de(document);else{var ee=function(){de(document.body)};window.HTMLImports?window.HTMLImports.whenReady(ee):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){ee();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else ee()})}Yd=function(){be(ce.takeRecords())}};var fe={};var ge=Promise.resolve();function he(a){if(a=fe[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function ie(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function je(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,ge.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var ke={},le=new Xd;function Y(){this.xa={};this.C=document.documentElement;var a=new Lc;a.rules=[];this.s=Gd(this.C,new U(a));this.Z=!1;this.b=this.g=null}k=Y.prototype;k.flush=function(){Yd()};k.$a=function(a){var b=this.xa[a]=(this.xa[a]||0)+1;return a+"-"+b};k.Fb=function(a){return gd(a)};k.Rb=function(a){return O(a)};
k.Za=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var d=a[c];if(d.hasAttribute("shady-unscoped")){if(!L){var e=d.textContent;if(!fd.has(e)){fd.add(e);var f=document.createElement("style");f.setAttribute("shady-unscoped","");f.textContent=e;document.head.appendChild(f)}d.parentNode.removeChild(d)}}else b.push(d.textContent),d.parentNode.removeChild(d)}return b.join("").trim()};
k.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
k.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!M){L||X[b]||(X[b]=kd(b));a._prepared=!0;a.name=b;a["extends"]=c;fe[b]=a;var d=S(a),e=qd(d);c={is:b,"extends":c};var f=this.Za(a)+(ke[b]||"");this.I();if(!e){var g;if(g=!d)g=ad.test(f)||$c.test(f),ad.lastIndex=0,$c.lastIndex=0;var h=Mc(f);g&&N&&this.g&&this.g.transformRules(h,b);a._styleAst=h}g=[];N||(g=Kd(a._styleAst));if(!g.length||N)b=this.ab(c,a._styleAst,L?a.content:null,X[b]||null,d,e?f:""),a._style=b;a.mb=g}};
k.Lb=function(a,b){ke[b]=a.join(" ")};k.prepareTemplateDom=function(a,b){if(!M){var c=S(a);L||"shady"===c||a._domPrepared||(a._domPrepared=!0,sd(a.content,b))}};k.ab=function(a,b,c,d,e,f){f=vd(a,b,null,e,f);return f.length?id(f,a.is,c,d):null};k.va=function(a){var b=R(a),c=b.is;b=b.L;var d=X[c]||null,e=fe[c];if(e){c=e._styleAst;var f=e.mb;e=S(e);b=new U(c,d,f,b,e);Gd(a,b);return b}};
k.Va=function(){return!this.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim?(this.g=window.ShadyCSS.ApplyShim,this.g.invalidCallback=he,!0):!1};k.Wa=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.Ga(b)},this.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.Z)&&a.flushCustomStyles()})})};k.I=function(){var a=this.Va();this.Wa();return a};
k.flushCustomStyles=function(){if(!M){var a=this.I();if(this.b){var b=this.b.processStyles();!a&&!this.b.enqueued||qd(this.s.cssBuild)||(N?this.s.cssBuild||this.tb(b):(this.qb(b),this.ea(this.C,this.s),this.Na(b),this.Z&&this.styleDocument()),this.b.enqueued=!1)}}};
k.qb=function(a){var b=this;a=a.map(function(c){return b.b.getStyleForCustomStyle(c)}).filter(function(c){return!!c});a.sort(function(c,d){c=d.compareDocumentPosition(c);return c&Node.DOCUMENT_POSITION_FOLLOWING?1:c&Node.DOCUMENT_POSITION_PRECEDING?-1:0});this.s.m.rules=a.map(function(c){return gd(c)})};
k.styleElement=function(a,b){if(M){if(b){V(a)||Gd(a,new U(null));var c=V(a);this.ta(c,b);me(this,a,c)}}else if(c=V(a)||this.va(a))this.aa(a)||(this.Z=!0),b&&this.ta(c,b),N?me(this,a,c):(this.flush(),this.ea(a,c),c.ha&&c.ha.length&&this.Oa(a,c))};k.ta=function(a,b){a.H=a.H||{};Object.assign(a.H,b)};
function me(a,b,c){var d=R(b).is;if(c.H){var e=c.H,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}if(((e=fe[d])||a.aa(b))&&(!e||""===S(e))&&e&&e._style&&!ie(e)){if(ie(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)a.I(),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=vd(b,c.m),je(e);L&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=vd(b,c.m));c.m=e._styleAst}}
k.ca=function(a){return(a=od(a).getRootNode().host)?V(a)||this.va(a)?a:this.ca(a):this.C};k.aa=function(a){return a===this.C};
k.Oa=function(a,b){var c=R(a).is,d=le.fetch(c,b.v,b.ha),e=d?d.styleElement:null,f=b.l;b.l=d&&d.l||this.$a(c);var g=b.l;var h=Ud;h=e?e.textContent||"":Sd(h,a,b.v,g);var m=V(a),l=m.F;l&&!L&&l!==e&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));L?m.F?(m.F.textContent=h,e=m.F):h&&(e=id(h,g,a.shadowRoot,m.placeholder)):e?e.parentNode||(Jd&&-1<h.indexOf("@media")&&(e.textContent=h),jd(e,null,m.placeholder)):h&&(e=id(h,g,null,m.placeholder));e&&(e._useCount=e._useCount||0,m.F!=
e&&e._useCount++,m.F=e);g=e;L||(e=b.l,m=h=a.getAttribute("class")||"",f&&(m=h.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),m+=(m?" ":"")+"x-scope "+e,h!==m&&nd(a,m));d||le.store(c,b.v,g,b.l);return g};k.ea=function(a,b){var c=this.ca(a),d=V(c),e=d.v;c===this.C||e||(this.ea(c,d),e=d.v);c=Object.create(e||null);e=Rd(a,b.m,b.cssBuild);a=Pd(d.m,a).u;Object.assign(c,e.Hb,a,e.Nb);this.jb(c,b.H);a=Ud;d=Object.getOwnPropertyNames(c);e=0;for(var f;e<d.length;e++)f=d[e],c[f]=Nd(a,c[f],c);b.v=c};
k.jb=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};k.styleDocument=function(a){this.styleSubtree(this.C,a)};k.styleSubtree=function(a,b){var c=od(a),d=c.shadowRoot,e=this.aa(a);(d||e)&&this.styleElement(a,b);if(a=e?c:d)for(a=Array.from(a.querySelectorAll("*")).filter(function(f){return od(f).shadowRoot}),b=0;b<a.length;b++)this.styleSubtree(a[b])};k.tb=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.sb(c)}};
k.Na=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&Td(c,this.s.v)}};k.Ga=function(a){var b=this,c=S(a);c!==this.s.cssBuild&&(this.s.cssBuild=c);if(!qd(c)){var d=gd(a);P(d,function(e){if(L)Fd(e);else{var f=T;e.selector=e.parsedSelector;Fd(e);f.za(e,f.yb)}N&&""===c&&(b.I(),b.g&&b.g.transformRule(e))});N?a.textContent=O(d):this.s.m.rules.push(d)}};k.sb=function(a){if(N&&this.g){var b=gd(a);this.I();this.g.transformRules(b);a.textContent=O(b)}};
k.getComputedStyleValue=function(a,b){var c;N||(c=(V(a)||V(this.ca(a))).v[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};k.Qb=function(a,b){var c=od(a).getRootNode();b=b?("string"===typeof b?b:String(b)).split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===T.M){c=d[e+1];break}}}c&&b.push(T.M,c);N||(c=V(a))&&c.l&&b.push(Ud.Ja,c.l);nd(a,b.join(" "))};k.wb=function(a){return V(a)};
k.Pb=function(a,b){T.element(a,b)};k.Tb=function(a,b){T.element(a,b,!0)};k.Ob=function(a){return ae(a)};k.Eb=function(a){return $d(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Qb;
Y.prototype._styleInfoForNode=Y.prototype.wb;Y.prototype.transformCustomStyleForDocument=Y.prototype.Ga;Y.prototype.getStyleAst=Y.prototype.Fb;Y.prototype.styleAstToString=Y.prototype.Rb;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Y.prototype.scopeNode=Y.prototype.Pb;Y.prototype.unscopeNode=Y.prototype.Tb;Y.prototype.scopeForNode=Y.prototype.Ob;Y.prototype.currentScopeForNode=Y.prototype.Eb;Y.prototype.prepareAdoptedCssText=Y.prototype.Lb;
Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return L}},nativeCss:{get:function(){return N}}});var Z=new Y,ne,oe;window.ShadyCSS&&(ne=window.ShadyCSS.ApplyShim,oe=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:N,nativeShadow:L,cssBuild:Zc,disableRuntime:M};ne&&(window.ShadyCSS.ApplyShim=ne);oe&&(window.ShadyCSS.CustomStyleInterface=oe);})();
//# sourceMappingURL=webcomponents-sd.js.sourcemap
