-- format "progress:%\n" 3
-- mcProgRad.form.invalidate()
-- mcProgRad.progressTo 60 msg:"Processing..."
	-- mcProgRad.progressTo 100 msg:"Processing Finished:"
	-- mcProgRad.progressTo 100 msg:"Processing...please wait..." confirm:true showButton:false clr:green
	-- mcProgRad.progressTo 100 msg:"Collapse Objects Is Finished!" confirm:true showButton:true clr:green
	
-- mousehook.mouseops.release()
--mcPopUp.close()
saveMaxFile "c:/temp/reco.max" useNewFile:false