Micra::Core::Node
bool Micra.Core.Node.IsRoot
bool Micra.Core.Node.IsTopParent
Node Micra.Core.Node.TopParent
Node Micra.Core.Node.Parent
IEnumerable<Node> Micra.Core.Node.Children
IEnumerable<Node> Micra.Core.Node.NodeTree
IEnumerable<ReferenceTarget> Micra.Core.Node.NodeReferenceTree
IEnumerable<Node> Micra.Core.Node.Nodes
Referenced by Micra.Core.SerializableModel.SerializableModel.
Node Micra.Core.Node.GetChild(int i)
void Micra.Core.Node.Attach(Node n)
void Micra.Core.Node.Attach(Node n, bool keepTM)
void Micra.Core.Node.Detach()
References Micra.Core.Kernel.Now.
void Micra.Core.Node.Detach(TimeValue t)
void Micra.Core.Node.Detach(TimeValue t, bool keepTM)
Node Micra.Core.Node.AddNewNode(SceneObject o, string name)
Node Micra.Core.Node.AddNewNode(SceneObject o)
References Micra.Core.Kernel._Interface, Micra.Core.SceneObject._Object.
IEnumerable<Modifier> Micra.Core.Node.Modifiers
void Micra.Core.Node.AddModifier(Modifier m)
void Micra.Core.Node.DeleteModifier(Modifier m)
Matrix3 Micra.Core.Node.NodeTransform
Matrix3 Micra.Core.Node.ObjectTransform
Matrix3 Micra.Core.Node.GetNodeTransform(TimeValue t)
void Micra.Core.Node.SetNodeTransform(Matrix3 m, TimeValue t)
Matrix3 Micra.Core.Node.GetNodeTransform(TimeValue t, out Interval validity)
Matrix3 Micra.Core.Node.GetObjectTransform(TimeValue t)
Matrix3 Micra.Core.Node.GetObjectTransform(TimeValue t, out Interval validity)
Material Micra.Core.Node.Material
SerializableModel Micra.Core.Node.GetSerializableModel()
SerializableScene Micra.Core.Node.GetSerializableScene()
IINode Micra.Core.Node._IINode
This is a handle to the low-level node managed by Autodesk.Max
String Micra.Core.Node.Name
String Micra.Core.Node.UserPropertyBuffer
bool Micra.Core.Node.Selected
bool Micra.Core.Node.Visible
Referenced by Micra.Core.ObjOps.SelectNodes.
bool Micra.Core.Node.Frozen
bool Micra.Core.Node.BoxMode
bool Micra.Core.Node.AllEdges
NodeVisibility Micra.Core.Node.Visibility
bool Micra.Core.Node.IsBone
Color Micra.Core.Node.Wirecolor
ulong Micra.Core.Node.NodeHandle
NodeUserData Micra.Core.Node.UserData
SceneObject Micra.Core.Node.Object
Geometry Micra.Core.Node.Geometry
Micra.Core.Node.Node(IINode x)
void Micra.Core.Node.InvalidateObjCache()
static Node Micra.Core.Node.Create(SceneObject o)
Creates a node attached to a particular scene object.
o
static Node Micra.Core.Node.Create(SceneObject o, string name)
Creates a named node attached to a particular scene object.
o name
void Micra.Core.Node.FlagForeground(TimeValue t, bool notify)
void Micra.Core.Node.FlagForeground(TimeValue t)
References Micra.Core.Node.FlagForeground.
Referenced by Micra.Core.Node.FlagForeground.
void Micra.Core.Node.FlagForeground()
References Micra.Core.Node.FlagForeground, Micra.Core.Kernel.Now.
Referenced by Micra.Core.Node.FlagForeground.
void Micra.Core.Node.SelectOnly()
void Micra.Core.Node.Delete()
void Micra.Core.Node.Delete(TimeValue t)
void Micra.Core.Node.Delete(TimeValue t, bool keepChildrenPositions)
string Micra.Core.Node.ClassOf()
Referenced by Micra.Core.SceneObject.HideFaces, Micra.Core.SceneObject.UnhideFaces.
string Micra.Core.Node.SuperClassOf()
bool Micra.Core.Node.IsClassOf(ClassID id)
Referenced by Micra.Tools.CsharpToMaxTest.BtnGetFaceArea_Click, Micra.Core.GeoOps.GetSelectedEdges, Micra.Core.GeoOps.SelectSimillarEdges.
bool Micra.Core.Node.IsSuperClassOf(SuperClassID id)
bool Micra.Core.Node.IsEditable(bool baseObject=false, bool modPolyOrMesh=false)
Use this Method to filter objects with Editable_Poly and Editable_Mesh class
example: if ( !node.IsEditable() ) return; param: baseObject TODO check base of object (allow to work bellow modifiers)param: modPolyOrMesh TODO check modifier of object (editable_poy and editable_mesh modifiers)
References Micra.Core.ClassID.EditableMesh, Micra.Core.ClassID.EditablePoly.
Referenced by Micra.Tools.CsharpToMaxTest.BtnSelSimElements_Click.
void Micra.Core.Node.Move(Point3 pt)
void Micra.Core.Node.Move(Point3 pt, TimeValue t)
References Micra.Core.Point3._IPoint3.
IObject Micra.Core.Node.GetObjectRef()
Mesh Micra.Core.Node.GetMesh()
Mesh Micra.Core.Node.GetMesh(TimeValue t)
Poly Micra.Core.Node.GetPoly()
IMesh Micra.Core.Node.GetImesh()
Referenced by Micra.Core.GeoOps.GetSelectedEdges.
IMesh Micra.Core.Node.GetImesh(TimeValue t)
IMNMesh Micra.Core.Node.GetIpoly()
Referenced by Micra.Core.GeoOps.GetSelectedEdges.
IMNMesh Micra.Core.Node.GetIpoly(TimeValue t)
Node Micra.Core.Node.CreateInstance()