//
// Copyright 2012 Autodesk, Inc.  All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.  
//

namespace Micra.Core.Enums {
    public enum EnumRefMsg {
        REFMSG_LOOPTEST = 0x00000010,
        //This tests for a cyclic reference. It will return REF_FAIL if there is a loop. More...

        REFMSG_TARGET_DELETED = 0x00000020,
        //This message is sent when a ReferenceTarget is deleted. More...

        REFMSG_MODAPP_DELETING = 0x00000021,
        //Used Internally. More...

        REFMSG_EVAL = 0x00000030,
        //Used Internally. More...

        REFMSG_RESET_ORIGIN = 0x00000040,
        //Used Internally. More...

        REFMSG_CHANGE = 0x00000050,
        //Sent to dependents of a ReferenceTarget that has changed in some way. More...

        REFMSG_FLAGDEPENDENTS = 0x00000070,
        //Used Internally. More...

        REFMSG_TARGET_SELECTIONCHANGE = 0x00000080,
        //Used Internally. More...

        REFMSG_BEGIN_EDIT = 0x00000090,
        //This is used by modifiers to indicate when they are beginning an edit. More...

        REFMSG_END_EDIT = 0x000000A0,
        //This is used by modifiers to indicate when they are ending an edit. More...

        REFMSG_DISABLE = 0x000000B0,
        //Used Internally. More...

        REFMSG_ENABLE = 0x000000C0,
        //Used Internally. More...

        REFMSG_TURNON = 0x000000D0,
        //Used Internally. More...

        REFMSG_TURNOFF = 0x000000E0,
        //Used Internally. More...

        REFMSG_LOOKAT_TARGET_DELETED = 0x000000F0,
        //Used Internally. More...

        REFMSG_INVALIDATE_IF_BG = 0x000000F1,
        //Used Internally. More...

        REFMSG_MOD_DISPLAY_ON = 0x000000F2,
        //This is used by modifiers to indicate that their apparatus (gizmo) is displayed. More...

        REFMSG_MOD_DISPLAY_OFF = 0x000000F3,
        //This is used by modifiers to indicate that their apparatus (gizmo) is no longer displayed. More...

        REFMSG_MOD_EVAL = 0x000000F4,
        //Modifier uses this to tell Modapps to call their Eval() procedure. More...

        REFMSG_IS_OK_TO_CHANGE_TOPOLOGY = 0x000000F5,
        //Ask if it is ok to change topology. More...

        REFMSG_NODE_LINK = 0x000000F6,
        //Sent by a node when it has a child linked to it or unlinked from it. More...

        REFMSG_NODE_NAMECHANGE = 0x000000F7,
        //Sent by a node when it's name has been changed. More...

        REFMSG_OBREF_CHANGE = 0x000000F8,
        //DEPRECATED Sent by a node (or derived object) when the object it references changes. More...

        REFMSG_MODIFIER_ADDED = 0x000000F9,
        //Sent by a derived object when a modifier is a added or deleted. More...

        REFMSG_CONTROLREF_CHANGE = 0x000000FA,
        //Sent when an animatable switches controllers for one of it's parameters. More...

        REFMSG_GET_PARAM_NAME = 0x000000FB,
        //A parameter block sends the message to it's client when it needs the anim name of the ith parameter. More...

        REFMSG_GET_PARAM_DIM = 0x000000FC,
        //A parameter block sends this message to it's client when it needs to know the dimension type of the ith parameter. More...

        REFMSG_GET_CONTROL_DIM = 0x000000FD,
        //A controller can send this to it's client to get it's param dimension. More...

        REFMSG_TM_CHANGE = 0x000000FE,
        //Sent when a Nodes transform matrix (TM) has changed in a different time. More...

        REFMSG_RANGE_CHANGE = 0x000000FF,
        //A node sends this message when it's animation range changes. More...

        REFMSG_LINEHEIGHT_CHANGE = 0x00000100,
        //Sent to the tree view when an animatable's line height changes. More...

        REFMSG_BECOMING_ANIMATED = 0x00000101,
        //A controller should send this message to the track view when it becomes animated. More...

        REFMSG_SUBANIM_STRUCTURE_CHANGED = 0x00000102,
        //Used in the TrackView to regenerate an objects sub components. More...

        REFMSG_REF_DELETED = 0x00000103,
        //A target has had a reference deleted. More...

        REFMSG_REF_ADDED = 0x00000104,
        //A target has had a reference added. More...

        REFMSG_BRANCHED_HISTORY_CHANGED = 0x00000105,
        //Sent by an object that provides branching in the history to notify that the structure of the branches changed. More...

        REFMSG_NODEINSELSET_CHANGED = 0x00000106,
        //The selection set sends this notification when it receives REFMSG_CHANGE from an item in the selection set. More...

        REFMSG_TEST_DEPENDENCY = 0x00000107,
        //This method is used to see if this reference target depends on something. More...

        REFMSG_WANT_SHOWPARAMLEVEL = 0x00000108,
        //Queries whether to display "Parameters" in the track view. More...

        REFMSG_BEFORE_PASTE = 0x00000109,
        //Sent before a paste has been done. More...

        REFMSG_NOTIFY_PASTE = 0x0000010A,
        //Sent after a paste has been done. More...

        REFMSG_UV_SYM_CHANGE = 0x0000010B,
        //Sent when a UV Generator changes symmetry, so interactive texture display updates. More...

        REFMSG_GET_NODE_NAME = 0x0000010C,
        //Gets the node's name. More...

        REFMSG_SEL_NODES_DELETED = 0x0000010D,
        //Sent by the selection set whenever it has just deleted nodes. More...

        REFMSG_PRENOTIFY_PASTE = 0x0000010E,
        //Sent before a reference target is pasted. Sent by the target about to be replaced. More...

        REFMSG_SHAPE_START_CHANGE = 0x0000010F,
        //Sent when a shape starts changing. More...

        REFMSG_SHAPE_END_CHANGE = 0x00000110,
        //Sent when a shape stops changing. More...

        REFMSG_TEXMAP_REMOVED = 0x00000111,
        //A texture map has been removed. More...

        REFMSG_FLAG_NODES_WITH_SEL_DEPENDENTS = 0x00000112,
        //Sent by an unselected node to see if any selected nodes depend on it. More...

        REFMSG_CONTAINED_SHAPE_POS_CHANGE = 0x00000120,
        //Sent by objects which contain shapes when the shape position changes. More...

        REFMSG_CONTAINED_SHAPE_SEL_CHANGE = 0x00000121,
        //Sent by objects which contain shapes when the shape position changes. More...

        REFMSG_CONTAINED_SHAPE_GENERAL_CHANGE = 0x00000122,
        //Sent by objects which contain shapes when general changes occur. More...

        REFMSG_SELECT_BRANCH = 0x00000130,
        //Select sub-object branch. More...

        REFMSG_MOUSE_CYCLE_STARTED = 0x00000140,
        //Sent when a user begins a mouse operation in the viewport. More...

        REFMSG_MOUSE_CYCLE_COMPLETED = 0x00000150,
        //Sent when a user ends a mouse operation in the viewport. More...

        REFMSG_CHECK_FOR_INVALID_BIND = 0x00000161,
        //Sent when linking nodes. More...

        REFMSG_OBJECT_CACHE_DUMPED = 0x00000162,
        //Sent when a cache is dumped in the pipeline. More...

        REFMSG_SFX_CHANGE = 0x00000170,
        //Sent by Atmospheric or Effect when it makes or deletes a reference to a node. More...

        REFMSG_OBJXREF_UPDATEMAT = 0x00000180,
        //For internal use only. More...

        REFMSG_OBJXREF_UPDATECTRL = 0x00000181,
        //For internal use only. More...

        REFMSG_OBJECT_REPLACED = 0x00000200,
        //Sent when objects are replaced from another scene (File->Replace). More...

        REFMSG_NODE_WIRECOLOR_CHANGED = 0x00000210,
        //Sent when nodes wireframe color is changed. More...

        REFMSG_NUM_SUBOBJECTTYPES_CHANGED = 0x00000211,
        //Indicates that the subobject types have changed and that the StackView should be updated. More...

        REFMSG_GET_NODE_HANDLE = 0x00000220,
        //Returns a unique (per session) node handle integer. More...

        REFMSG_END_MODIFY_PARAMS = 0x00000230,
        //This will cause EndEditParams to be called on the object displayed in the modify panel. More...

        REFMSG_BEGIN_MODIFY_PARAMS = 0x00000231,
        //This will cause BeginEditParams to be called on the object displayed in the modify panel. More...

        REFMSG_TAB_ELEMENT_NULLED = 0x00000232,
        //Deprecated name, replaced by REFMSG_CONTAINER_ELEMENT_NULLED in 3ds Max 2015, since this name is inaccurate. More...

        REFMSG_NODE_HANDLE_CHANGED = 0x00000233,
        //Sent to merged objects so that they can convert node handles. More...

        REFMSG_NODE_WSCACHE_UPDATED = 0x00000234,
        //The pipeline was reevaluated and the wscache was updated. More...

        REFMSG_NODE_MATERIAL_CHANGED = 0x00000235,
        //This notification is sent after a new material was assigned to a node. More...

        REFMSG_SUBANIM_NUMBER_CHANGED = 0x00000236,
        //This notification is sent to dependents when a subanim's changes order. More...

        REFMSG_NODE_FLAGOMB_RENDER = 0x00000237,
        //A Node is rendered with motion blur. More...

        REFMSG_NODE_GI_PROP_CHANGED = 0x00000238,
        //For Internal use only. More...

        REFMSG_KEY_SELECTION_CHANGED = 0x00000239,
        //Sent when key selection changes. More...

        REFMSG_NODE_RENDERING_PROP_CHANGED = 0x00000240,
        //Sent AFTER the Node Rendering Properties have changed The part id will contain information about the property that has changed. More...

        REFMSG_NODE_DISPLAY_PROP_CHANGED = 0x00000241,
        //Notification sent AFTER the Node Display Properties have changed. More...

        REFMSG_NODE_LAYER_PROP_CHANGED = 0x00000242,
        //Sent AFTER an ILayer's properties have changed Sent only to the immediate dependents of the ILayer. More...

        REFMSG_MXS_CUSTATTRIB_CHANGE = 0x00000250,
        //Message type propagated to dependents of scripted Custom Attribute (CA) when CA gets a REFMSG_CHANGE. More...

        REFMSG_NODE_PRE_DELETE = 0x00000255,
        //This message is sent immediately prior to a node being deleted. More...

        REFMSG_LOCKED = 0x00000260,
        //This message is sent after an item has been locked. More...

        REFMSG_UNLOCKED = 0x00000261,
        //This message is sent after an item has been unlocked. More...

        REFMSG_OBJECT_DEFINITION_CHANGE_BEGIN = 0x00000270,
        //This message is sent immediately before an object instance is updated to a new object definition. More...

        REFMSG_OBJECT_DEFINITION_CHANGE_END = 0x00000271,
        //This message is sent immediately after an object instance is updated to a new object definition. More...

        REFMSG_DISPLAY_MATERIAL_CHANGE = 0x00000275,
        //Notification sent when any parameters of the material or texture map changed. More...

        REFMSG_USER = 0x00010000
        //Message numbers above this value can be defined for use by sub-classes, below are reserved. More...
    }
}
